# Generated by Django 5.1.3 on 2025-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.TextField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='detection/Images')),
            ],
        ),
    ]
