# Generated by Django 5.1.3 on 2025-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='diseases',
            field=models.CharField(max_length=50),
        ),
    ]
