# Generated by Django 3.1.12 on 2025-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detection_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='diseases',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
