# Generated by Django 5.1.6 on 2025-05-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_detection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to='detection/Images'),
        ),
    ]
