# Generated by Django 5.1.6 on 2025-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='llm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusetion', models.CharField(default='', max_length=50)),
                ('answer', models.ImageField(default='', upload_to='detection/Images')),
            ],
        ),
    ]
